
export const generateConsentText = (procedureType: string, patientName: string): string => {
  switch (procedureType) {
    case 'Toxina Botulínica (Botox)':
      return `TERMO DE CONSENTIMENTO LIVRE E ESCLARECIDO\nPROCEDIMENTO: APLICAÇÃO DE TOXINA BOTULÍNICA (BOTOX)\n\nEu, ${patientName}, declaro que fui informado(a) pelo(a) médico(a) sobre os detalhes do procedimento de aplicação de toxina botulínica, seus benefícios, riscos, possíveis complicações e alternativas. Compreendo que:\n\n1. A toxina botulínica é utilizada para relaxamento temporário da musculatura facial, reduzindo linhas de expressão e rugas dinâmicas;\n\n2. O efeito do procedimento é temporário, durando em média de 3 a 6 meses, sendo necessária nova aplicação para manutenção dos resultados;\n\n3. Possíveis efeitos colaterais incluem: dor leve no local da aplicação, edema (inchaço), eritema (vermelhidão), hematoma (roxo), assimetria facial temporária, ptose palpebral (queda da pálpebra), cefaleia (dor de cabeça);\n\n4. O resultado final do procedimento será observado entre 7 a 15 dias após a aplicação;\n\n5. Deverei seguir todas as recomendações pós-procedimento fornecidas pelo(a) médico(a), incluindo não massagear a área tratada, não se deitar ou abaixar a cabeça nas primeiras 4 horas, e evitar atividade física intensa nas primeiras 24 horas.\n\nDeclaro que tive a oportunidade de esclarecer todas as minhas dúvidas relativas ao procedimento e que as informações que prestei sobre meu histórico de saúde são verdadeiras, tendo informado sobre alergias, medicamentos em uso, gravidez/amamentação e condições médicas relevantes.`;
      
    case 'Preenchimento Facial':
      return `TERMO DE CONSENTIMENTO LIVRE E ESCLARECIDO\nPROCEDIMENTO: PREENCHIMENTO FACIAL COM ÁCIDO HIALURÔNICO\n\nEu, ${patientName}, declaro que fui informado(a) pelo(a) médico(a) sobre os detalhes do procedimento de preenchimento facial com ácido hialurônico, seus benefícios, riscos, possíveis complicações e alternativas. Compreendo que:\n\n1. O preenchimento facial com ácido hialurônico é utilizado para restaurar volume facial, corrigir sulcos, rugas e melhorar o contorno facial;\n\n2. O efeito do procedimento é temporário, durando em média de 6 a 18 meses, dependendo da área tratada e do produto utilizado;\n\n3. Possíveis efeitos colaterais incluem: dor no local da aplicação, edema (inchaço), eritema (vermelhidão), hematoma (roxo), sensibilidade local, assimetria, nódulos ou granulomas;\n\n4. Em casos muito raros, podem ocorrer complicações graves como necrose tecidual e obstrução vascular, que requerem tratamento imediato;\n\n5. O resultado final do procedimento será observado após a resolução do edema inicial, aproximadamente 7 a 14 dias;\n\n6. Deverei seguir todas as recomendações pós-procedimento fornecidas pelo(a) médico(a), incluindo evitar exposição solar intensa, saunas, atividade física e consumo de álcool nas primeiras 24 horas.\n\nDeclaro que tive a oportunidade de esclarecer todas as minhas dúvidas relativas ao procedimento e que as informações que prestei sobre meu histórico de saúde são verdadeiras, tendo informado sobre alergias, medicamentos em uso, gravidez/amamentação e condições médicas relevantes.`;
      
    default:
      return `TERMO DE CONSENTIMENTO LIVRE E ESCLARECIDO\nPROCEDIMENTO: ${procedureType.toUpperCase()}\n\nEu, ${patientName}, declaro que fui informado(a) pelo(a) médico(a) sobre os detalhes do procedimento, seus benefícios, riscos, possíveis complicações e alternativas. Compreendo que este procedimento possui características específicas que me foram explicadas detalhadamente.\n\nFui informado(a) sobre possíveis efeitos colaterais, duração esperada dos resultados e cuidados necessários pós-procedimento. Tive a oportunidade de esclarecer todas as minhas dúvidas e fui informado(a) sobre alternativas terapêuticas para minha condição.\n\nDecido, de forma livre e esclarecida, consentir com a realização do procedimento proposto, estando ciente de que posso revogar este consentimento a qualquer momento antes da realização do procedimento, sem penalização ou prejuízo ao meu atendimento.`;
  }
};
