// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://grzkmetsgooretttrjiv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdyemttZXRzZ29vcmV0dHRyaml2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0NTI5NjQsImV4cCI6MjA3MTAyODk2NH0.O3X90dhlJAxH1W8Bw8jV9jFZjR_zRCjPBsgQI8DcvjE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});